spring.application.name=DriverService
jwt.secret=Sec32r43e43t43K43e43y54
server.port=8081

# ========= DATABASE CONFIG =========
spring.database.url=jdbc:mysql://localhost:3306/driverservice
spring.datasource.username=root
spring.datasource.password=Ashish@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA / HIBERNATE CONFIG ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ========== LOGGING CONFIG ==========
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

